# Private witness values for proof generation

# This should match the verifier_image_hash for this demo
signed_image_hash = ["0x12", "0x34", "0x56", "0x78", "0x9a", "0xbc", "0xde", "0xf0", "0x12", "0x34", "0x56", "0x78", "0x9a", "0xbc", "0xde", "0xf0", "0x12", "0x34", "0x56", "0x78", "0x9a", "0xbc", "0xde", "0xf0", "0x12", "0x34", "0x56", "0x78", "0x9a", "0xbc", "0xde", "0xf0"]

# Specific timestamp within the bounds (June 15, 2023 12:30:45 UTC)
signed_timestamp = "1686834645"

# Example device identifier
signed_device_id = "12345678"

# Specific GPS coordinates within the bounds (Market St, San Francisco)
signed_latitude = "37774929"    # 37.774929 N
signed_longitude = "-122419416" # 122.419416 W

# GPS must be enabled for our circuit to pass
signed_gps_enabled = true

# This would be a real ECDSA signature in practice
# For demonstration, we'll use placeholder values
signature = ["0x01", "0x02", "0x03", "0x04", "0x05", "0x06", "0x07", "0x08", "0x09", "0x0a", "0x0b", "0x0c", "0x0d", "0x0e", "0x0f", "0x10", 
             "0x11", "0x12", "0x13", "0x14", "0x15", "0x16", "0x17", "0x18", "0x19", "0x1a", "0x1b", "0x1c", "0x1d", "0x1e", "0x1f", "0x20",
             "0x21", "0x22", "0x23", "0x24", "0x25", "0x26", "0x27", "0x28", "0x29", "0x2a", "0x2b", "0x2c", "0x2d", "0x2e", "0x2f", "0x30",
             "0x31", "0x32", "0x33", "0x34", "0x35", "0x36", "0x37", "0x38", "0x39", "0x3a", "0x3b", "0x3c", "0x3d", "0x3e", "0x3f", "0x40"]

# Example device public key (X and Y coordinates)
# In a real implementation, this would be the actual public key
device_public_key_x = ["0xa1", "0xa2", "0xa3", "0xa4", "0xa5", "0xa6", "0xa7", "0xa8", "0xa9", "0xaa", "0xab", "0xac", "0xad", "0xae", "0xaf", "0xb0", 
                       "0xb1", "0xb2", "0xb3", "0xb4", "0xb5", "0xb6", "0xb7", "0xb8", "0xb9", "0xba", "0xbb", "0xbc", "0xbd", "0xbe", "0xbf", "0xc0"]

device_public_key_y = ["0xd1", "0xd2", "0xd3", "0xd4", "0xd5", "0xd6", "0xd7", "0xd8", "0xd9", "0xda", "0xdb", "0xdc", "0xdd", "0xde", "0xdf", "0xe0", 
                       "0xe1", "0xe2", "0xe3", "0xe4", "0xe5", "0xe6", "0xe7", "0xe8", "0xe9", "0xea", "0xeb", "0xec", "0xed", "0xee", "0xef", "0xf0"] 